name: CateringAdmin
description: A new Flutter project.
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.6.0
  get: ^4.6.5
  flutter_keyboard_visibility: ^5.4.1
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.5
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  flutter_easyloading: ^3.0.5
  firebase_messaging: ^14.6.8
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  image_card: ^0.0.4
  flutter_swipe_action_cell: ^3.1.2
  url_launcher: ^6.2.1
  get_storage: ^2.1.1
  image_picker: ^1.0.2
  device_info_plus: ^9.1.2
  intl: ^0.19.0
  permission_handler: ^10.4.3
  app_settings: ^5.0.0
  firebase_storage: ^11.6.0
  uuid: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^0.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/admin_logo.png"
  adaptive_icon_background: "assets/images/admin_background.png"
  min_sdk_android: 21


