// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDrvdDmiMm6RcFaReNT3XgZe_bM6k44qA',
    appId: '1:694528548354:web:eef1420bea84588ddf511b',
    messagingSenderId: '694528548354',
    projectId: 'daffodilcafe-73d7e',
    authDomain: 'daffodilcafe-73d7e.firebaseapp.com',
    storageBucket: 'daffodilcafe-73d7e.appspot.com',
    measurementId: 'G-VGYL5LP3B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc_ScHDEYWt-yHTnYLc70bchjxTA13CSY',
    appId: '1:694528548354:android:7a389c6845cc68a7df511b',
    messagingSenderId: '694528548354',
    projectId: 'daffodilcafe-73d7e',
    storageBucket: 'daffodilcafe-73d7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnr6K7kbfMAIh5e3e0OpLBOb6ZQ1xsoUc',
    appId: '1:694528548354:ios:7a08d2863425a9e0df511b',
    messagingSenderId: '694528548354',
    projectId: 'daffodilcafe-73d7e',
    storageBucket: 'daffodilcafe-73d7e.appspot.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnr6K7kbfMAIh5e3e0OpLBOb6ZQ1xsoUc',
    appId: '1:694528548354:ios:7a08d2863425a9e0df511b',
    messagingSenderId: '694528548354',
    projectId: 'daffodilcafe-73d7e',
    storageBucket: 'daffodilcafe-73d7e.appspot.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDrvdDmiMm6RcFaReNT3XgZe_bM6k44qA',
    appId: '1:694528548354:web:52632a950ce0d1fadf511b',
    messagingSenderId: '694528548354',
    projectId: 'daffodilcafe-73d7e',
    authDomain: 'daffodilcafe-73d7e.firebaseapp.com',
    storageBucket: 'daffodilcafe-73d7e.appspot.com',
    measurementId: 'G-W1CG0G7W2W',
  );

}